config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :notes

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :author, class_name: "User", foreign_key: "author_id"
end

app/models/user.rb
# -*- coding: utf-8 -*-

class User < ActiveRecord::Base
  
  has_many :notes, dependent: :destroy

  def admin_text
    return '有' if is_admin
    '無'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index 
    @notes = Note.all
  end

  def new
    @note = Note.new
  end

  def create
    note = Note.new
    note.title   = params['note']['title']
    note.content = params['note']['content']
    # 作成者IDを仮に1とする(あとで作成)
    note.author_id = 1
    note.save
    redirect_to notes_path
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    note = Note.find(params[:id])
    if note.update_attributes(user_params)
      redirect_to notes_path
    else
      render 'edit'
    end
  end

  def destroy 
    note = Note.find(params[:id])
    note.destroy
    redirect_to notes_path
  end

  def user_params
    params.require(:note).permit('title', 'content')
  end

end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    user = User.new
    user.account      = params['user']['account']
    user.mail_address = params['user']['mail_address']
    user.save
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.account      = params['user']['account']
    user.mail_address = params['user']['mail_address']
    user.save
    redirect_to users_path
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  #管理者かどうかの確認
  def is_admin
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kingyo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/edit.html.erb
<div class="container">
  <h1>ノートの編集</h1>
</div>

<%= form_for @note do |f| %>
  <div class="container bg-info">
    <div>
      <h3>タイトル</h3>
      <%= f.text_field :title, :class => "form-control" %>
    </div>
    <div>
      <h3>テキスト</h3>
      <%= f.text_area  :content, :class => "form-control" , :rows => "15"%>
    </div>
    <br />
  </div>
  <div class="container">
    <br />
    <%= f.submit '更新', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/notes/index.html.erb
<h1>ノートの一覧ページ</h1>

<%= link_to '新規作成', new_note_path, :class => "btn btn-primary", :type => "button" %>

<table class="table">
  <thead>
    <th>タイトル</th>
    <th>作成者ID</th>
    <th>更新日時</th>
    <th>編集</th>
    <th>削除</th>
  </thead>
  <tbody>
    <% @notes.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.author.account %></td>
        <td><%= item.updated_at %></td>
        <td><%= link_to '編集', edit_note_path(item.id), :class => "btn btn-success btn-xs" %></td>
        <td><%= link_to '削除', note_path(item.id), :method => :delete, data: { confirm: "#{item.title} を削除します" }, :class => "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/notes/new.html.erb
<div class="container">
  <h1>ノートの新規作成</h1>
</div>

<%= form_for @note do |f| %>
  <div class="container bg-info">
    <div>
      <h3>タイトル</h3>
      <%= f.text_field :title, :class => "form-control" %>
    </div>
    <div>
      <h3>テキスト</h3>
      <%= f.text_area  :content, :class => "form-control" , :rows => "15"%>
    </div>
    <br />
  </div>
  <div class="container">
    <br />
    <%= f.submit '登録', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザ編集</h1>

<%= form_for @user do |form| %>
  <div class="form-group">
    <label for="account">アカウント</label>
    <%= form.text_field :account, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label>メールアドレス</label>
    <%= form.text_field :mail_address, :class => "form-control"%>
  </div>
  <%= form.submit '登録', :class => "btn btn-danger" %>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<%= link_to '新規作成', new_user_path, :class => 'btn btn-primary'%> 

<table class="table">
  <thead>
    <th>アカウント</th>
    <th>メールアドレス</th>
    <th>管理者権限</th>
    <th>編集</th>
    <th>削除</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.account %></td>
        <td><%= user.mail_address %></td>
        <td><%= user.admin_text %></td>
        <td><%= link_to '編集', edit_user_path(user), :class => 'btn btn-warning btn-xs'%></td>
        <td><%= link_to '削除', user, method: :delete,
              data: { confirm: "本当に削除しますか？"}, :class => 'btn btn-danger btn-xs'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>ユーザ新規作成</h1>

<%= form_for @user do |f| %>
  <div>
    <label>アカウント</label>
    <%= f.text_field :account %>
  </div>
  <div>
    <label>メールアドレス</label>
    <%= f.text_field :mail_address %>
  </div>
  <%= f.submit '登録' %>
<% end %>